# Generated by Django 4.0.4 on 2022-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True), max_length=255),
        ),
    ]
