# Generated by Django 4.0.4 on 2022-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='graduations',
            field=models.ManyToManyField(to='person.graduation'),
        ),
    ]
