# Generated by Django 4.0.4 on 2022-05-15 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_graduation_person_person_graduations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='graduations',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), to='person.graduation'),
        ),
    ]
