# Generated by Django 4.0.4 on 2022-05-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_graduation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[('10', 'White'), ('I', 'Dan 1'), ("[('10', '10th GUP')]", 'Gup'), ("[('I', 'I DAN')]", 'Dan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
