# Generated by Django 4.0.4 on 2022-05-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_graduation_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
