# Generated by Django 4.0.4 on 2022-05-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_alter_graduation_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='graduation',
        ),
    ]
