# Generated by Django 4.0.4 on 2022-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_alter_graduation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[], default=None, max_length=20),
        ),
    ]
