# Generated by Django 4.0.4 on 2022-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_alter_graduation_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[('10 GUP', ' 10Th Gup'), ('9 GUP', ' 9Th Gup'), ('8 GUP', ' 8Th Gup'), ('7 GUP', ' 7Th Gup'), ('6 GUP', ' 6Th Gup'), ('5 GUP', ' 5Th Gup'), ('4 GUP', ' 4Th Gup'), ('3 GUP', ' 3Rd Gup'), ('2 GUP', ' 2Nd Gup'), ('1 GUP', ' 1St Gup'), ('I DAN', ' I Dan'), ('II DAN', ' Ii Dan'), ('III DAN', ' Iii Dan'), ('IV DAN', ' Iv Dan'), ('V DAN', ' V Dan'), ('VI DAN', ' Vi Dan'), ('VII DAN', ' Vii Dan'), ('VIII DAN', ' Viii Dan'), ('IX DAN', ' Ix Dan')], max_length=20, null=True),
        ),
    ]
