# Generated by Django 4.0.4 on 2022-05-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_alter_graduation_graduation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='graduation',
        ),
        migrations.AddField(
            model_name='graduation',
            name='apply_for',
            field=models.CharField(choices=[('10 GUP', ' 10Th Gup'), ('9 GUP', ' 9Th Gup'), ('8 GUP', ' 8Th Gup'), ('7 GUP', ' 7Th Gup'), ('6 GUP', ' 6Th Gup'), ('5 GUP', ' 5Th Gup'), ('4 GUP', ' 4Th Gup'), ('3 GUP', ' 3Rd Gup'), ('2 GUP', ' 2Nd Gup'), ('1 GUP', ' 1St Gup'), ('I DAN', ' I Dan'), ('II DAN', ' Ii Dan'), ('III DAN', ' Iii Dan'), ('IV DAN', ' Iv Dan'), ('V DAN', ' V Dan'), ('VI DAN', ' Vi Dan'), ('VII DAN', ' Vii Dan'), ('VIII DAN', ' Viii Dan'), ('IX DAN', ' Ix Dan')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='graduation_at_date',
            field=models.CharField(choices=[('10 GUP', ' 10Th Gup'), ('9 GUP', ' 9Th Gup'), ('8 GUP', ' 8Th Gup'), ('7 GUP', ' 7Th Gup'), ('6 GUP', ' 6Th Gup'), ('5 GUP', ' 5Th Gup'), ('4 GUP', ' 4Th Gup'), ('3 GUP', ' 3Rd Gup'), ('2 GUP', ' 2Nd Gup'), ('1 GUP', ' 1St Gup'), ('I DAN', ' I Dan'), ('II DAN', ' Ii Dan'), ('III DAN', ' Iii Dan'), ('IV DAN', ' Iv Dan'), ('V DAN', ' V Dan'), ('VI DAN', ' Vi Dan'), ('VII DAN', ' Vii Dan'), ('VIII DAN', ' Viii Dan'), ('IX DAN', ' Ix Dan')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='observation',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='graduation',
            name='qualification',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='graduation',
            name='status',
            field=models.CharField(choices=[('Approved', 'Passed'), ('Not Approved', 'Failed')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='certification_id',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
