# Generated by Django 4.0.4 on 2022-05-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_remove_graduation_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='observation',
            field=models.TextField(default='', max_length=255),
        ),
    ]
