# Generated by Django 4.0.4 on 2022-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_remove_graduation_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='observation',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='graduation',
            name='qualification',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
