# Generated by Django 4.0.4 on 2022-05-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0039_alter_person_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='observation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
