# Generated by Django 4.0.4 on 2022-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0042_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('0', 'O')], default=None, max_length=2, null=True),
        ),
    ]
