# Generated by Django 4.0.4 on 2022-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0044_alter_person_blood_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduation',
            old_name='graduation_at_date',
            new_name='current_graduation',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='evaluator',
        ),
        migrations.AddField(
            model_name='graduation',
            name='evaluators',
            field=models.ManyToManyField(related_name='evaluators', to='person.person'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
    ]
