# Generated by Django 4.0.4 on 2022-06-05 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('blood_type', models.CharField(choices=[('A', ' A Type'), ('B', ' B Type'), ('AB', ' Ab Type'), ('0', ' O Type')], default=None, max_length=2, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Instructor', ' Instructor'), ('Student', ' Student'), ('Unsuscribed', ' Unsuscribed'), ('Expulsed', ' Expulsed'), ('Guest', ' Guest')], default='Guest', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_graduation', models.CharField(choices=[('10 GUP', ' 10Th Gup'), ('9 GUP', ' 9Th Gup'), ('8 GUP', ' 8Th Gup'), ('7 GUP', ' 7Th Gup'), ('6 GUP', ' 6Th Gup'), ('5 GUP', ' 5Th Gup'), ('4 GUP', ' 4Th Gup'), ('3 GUP', ' 3Rd Gup'), ('2 GUP', ' 2Nd Gup'), ('1 GUP', ' 1St Gup'), ('I DAN', ' I Dan'), ('II DAN', ' Ii Dan'), ('III DAN', ' Iii Dan'), ('IV DAN', ' Iv Dan'), ('V DAN', ' V Dan'), ('VI DAN', ' Vi Dan'), ('VII DAN', ' Vii Dan'), ('VIII DAN', ' Viii Dan'), ('IX DAN', ' Ix Dan')], max_length=10, null=True)),
                ('apply_for', models.CharField(choices=[('10 GUP', ' 10Th Gup'), ('9 GUP', ' 9Th Gup'), ('8 GUP', ' 8Th Gup'), ('7 GUP', ' 7Th Gup'), ('6 GUP', ' 6Th Gup'), ('5 GUP', ' 5Th Gup'), ('4 GUP', ' 4Th Gup'), ('3 GUP', ' 3Rd Gup'), ('2 GUP', ' 2Nd Gup'), ('1 GUP', ' 1St Gup'), ('I DAN', ' I Dan'), ('II DAN', ' Ii Dan'), ('III DAN', ' Iii Dan'), ('IV DAN', ' Iv Dan'), ('V DAN', ' V Dan'), ('VI DAN', ' Vi Dan'), ('VII DAN', ' Vii Dan'), ('VIII DAN', ' Viii Dan'), ('IX DAN', ' Ix Dan')], max_length=10, null=True)),
                ('weight', models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True)),
                ('graduation_date', models.DateTimeField()),
                ('graduation_place', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Approved', ' Passed'), ('Not approved', ' Failed')], default='Not approved', max_length=20)),
                ('qualification', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('observation', models.TextField(blank=True, max_length=255, null=True)),
                ('certification_id', models.CharField(default=None, max_length=30)),
                ('evaluators', models.ManyToManyField(related_name='evaluators', to='school.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.person')),
            ],
        ),
    ]
