# Generated by Django 4.0.4 on 2022-05-15 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('0', 'O')], default=None, max_length=2)),
                ('observation', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Expulsed', 'Expulsed'), ('Guest', 'Guest')], default='Guest', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateTimeField()),
                ('certification_id', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=100)),
                ('graduation_place', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.person')),
            ],
        ),
    ]
