# Generated by Django 4.0.4 on 2022-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_graduation_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[('10', 'White'), ('I', 'Dan 1'), ("[('10', '10th GUP')]", 'Gup'), ("[('I', 'I DAN')]", 'Dan')], default=None, max_length=20),
        ),
    ]
