# Generated by Django 4.0.4 on 2022-05-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_graduation_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='graduation',
        ),
        migrations.AlterField(
            model_name='graduation',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.person'),
        ),
    ]
