# Generated by Django 4.0.4 on 2022-05-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_graduation_graduation_alter_graduation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.person'),
        ),
    ]
