# Generated by Django 4.0.4 on 2022-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_graduation_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[('10', 'White'), ('9', 'White Yellow'), ('8', 'Yellow'), ('7', 'Yellow Green'), ('6', 'Green'), ('5', 'Green Blue'), ('4', 'Blue'), ('3', 'Blue Red'), ('2', 'Red'), ('1', 'Red Black'), ('I', 'Dan 1'), ('II', 'Dan 2'), ('III', 'Dan 3'), ('IV', 'Dan 4'), ('V', 'Dan 5'), ('VI', 'Dan 6'), ('VII', 'Dan 7'), ('VIII', 'Dan 8'), ('IX', 'Dan 9')], default=None, max_length=20),
        ),
    ]
