# Generated by Django 4.0.4 on 2022-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_graduation_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='graduation',
            field=models.CharField(choices=[("['1er GUP']", 'Gups')], default=None, max_length=20),
        ),
    ]
