# Generated by Django 4.0.4 on 2022-05-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_remove_graduation_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='qualification',
        ),
    ]
