# Generated by Django 4.0.4 on 2022-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_alter_person_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A Type'), ('B', 'B Type'), ('AB', 'Ab Type'), ('0', 'O Type')], default=None, max_length=2, null=True),
        ),
    ]
