# Generated by Django 4.0.4 on 2022-05-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_rename_graduation_at_date_graduation_current_graduation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student'), ('Unsuscribed', 'Unsuscribed'), ('Expulsed', 'Expulsed'), ('Guest', 'Guest')], default='Guest', max_length=11),
        ),
    ]
